#!/bin/sh

qemu-system-x86_64 -m 1G -cpu host -smp 1 -enable-kvm -nic user,hostfwd=tcp::10022-:22 -drive format=raw,file=/home/ben/workspace/qemu/ubuntu2004.img -nographic
#qemu-system-x86_64 -m 1G -cpu host -smp 1 -enable-kvm -drive format=raw,file=/home/ben/workspace/qemu/ubuntu2004.img -display curses $@
