#!/bin/sh
#isofile=/home/ben/workspace/qemu/ubuntu2004.img

# qemu-system-x86_64 -m 1G -cpu host -smp 1 -enable-kvm -net nic,model=virtio -net bridge,br=br0 -drive format=raw,file="$1" -nographic
qemu-system-x86_64 -m 1G -cpu host -smp 1 -enable-kvm -nic user,hostfwd=tcp::$2-:22,hostfwd=tcp::1280-:80 -drive format=raw,file="$1" -nographic &

# qemu-system-x86_64 -m 1G -cpu host -smp 1 -enable-kvm -nic user,hostfwd=tcp::10022-:22 -drive format=raw,file=/home/ben/workspace/qemu/ubuntu2004.img -nographic
# qemu-system-x86_64 -m 1G -cpu host -smp 1 -enable-kvm -drive format=raw,file=/home/ben/workspace/qemu/ubuntu2004.img -display curses $@


# process
# $ qemu-img create -f raw ubuntu1804.img 5G
# Formatting 'ubuntu1804.img', fmt=raw size=5368709120

# $ du ubuntu1804.img
# 4       ubuntu1804.img

# $ qemu-system-x86_64 -m 1024 -cpu host -smp 2 -enable-kvm -cdrom /home/ben/Downloads/ubuntu-18.04.5-live-server-amd64.iso -boot order=d -drive file=ubuntu1804.img,format=raw
